import type { SchemaField, IntegrationType } from "@/types/integration.types";

export const INTEGRATION_SCHEMAS: Record<IntegrationType, SchemaField[]> = {
  QITAF: [
    {
      key: "environment",
      label: "Environment",
      type: "select",
      options: ["test", "production"],
      required: true,
      helperText: "Select 'test' during development and UAT phases",
    },
    {
      key: "apiBaseUrl",
      label: "API Base URL",
      type: "text",
      required: true,
      helperText: "STC Qitaf web service endpoint URL",
    },
    {
      key: "branchId",
      label: "Branch ID",
      type: "text",
      required: true,
      helperText: "Provided by STC Qitaf after registration",
    },
    {
      key: "terminalId",
      label: "Terminal ID (Teller ID)",
      type: "text",
      required: true,
      helperText: "Provided by STC Qitaf after registration",
    },
    {
      key: "timeoutSeconds",
      label: "Redemption Timeout (seconds)",
      type: "number",
      required: true,
      default: 60,
      helperText: "STC mandate: 60s. If no response, call Reverse automatically",
    },
    {
      key: "otpValidityMinutes",
      label: "OTP Validity (minutes)",
      type: "number",
      required: true,
      default: 3,
      helperText: "Qitaf OTP expires after 3 minutes",
    },
    {
      key: "pointToAmountRatio",
      label: "Points to SAR Ratio",
      type: "number",
      required: true,
      helperText: "Amount-to-QitafPoint ratio agreed with STC",
    },
    {
      key: "refundPeriodDays",
      label: "Refund Period (days)",
      type: "number",
      required: true,
      helperText: "Points are posted after this refund window expires",
    },
    {
      key: "certificate",
      label: "SSL Certificate (.pem / .crt)",
      type: "file",
      accept: ".pem,.crt,.cer",
      required: false,
      helperText: "Certificate Signing Request (CSR) file provided by STC",
    },
    {
      key: "testMsisdn",
      label: "Test Mobile Number (STC GSM)",
      type: "text",
      showWhen: { key: "environment", value: "test" },
      helperText: "Consumer STC number (without 966 country code)",
    },
    {
      key: "simCardSerial",
      label: "SIM Card Serial Number",
      type: "text",
      showWhen: { key: "environment", value: "test" },
      helperText: "18-digit serial printed on SIM card (from mySTC app)",
    },
  ],
  AL_FURSAN: [
    {
      key: "environment",
      label: "Environment",
      type: "select",
      options: ["test", "production"],
      required: true,
      helperText: "Select 'test' during development and UAT phases",
    },
    {
      key: "apiBaseUrl",
      label: "API Base URL",
      type: "text",
      required: true,
      helperText: "Al Fursan loyalty web service endpoint URL",
    },
    {
      key: "partnerId",
      label: "Partner ID",
      type: "text",
      required: true,
      helperText: "Provided by Al Fursan after registration",
    },
    {
      key: "apiKey",
      label: "API Key",
      type: "text",
      required: true,
      helperText: "API key for authenticating with Al Fursan services",
    },
    {
      key: "pointToMileRatio",
      label: "Points to Mile Ratio",
      type: "number",
      required: true,
      helperText: "Conversion ratio between loyalty points and Al Fursan miles",
    },
    {
      key: "timeoutSeconds",
      label: "Request Timeout (seconds)",
      type: "number",
      required: true,
      default: 60,
      helperText: "Maximum wait time before considering a request failed",
    },
  ],
};

export const INTEGRATION_TYPE_LABELS: Record<IntegrationType, string> = {
  QITAF: "STC Qitaf",
  AL_FURSAN: "Al Fursan",
};
